[project]
name = "asyncssh-executor"
version = "0.1.0"
description = "Module for async execution of commands over SSH"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncssh>=2.22.0",
]
